export const LOAD_CAMPUSES = 'LOAD_CAMPUSES';
export const UNLOAD = 'UNLOAD';
export const SINGLE_CAMPUS = 'SINGLE_CAMPUS';
export const CREATE_CAMPUS = 'CREATE_CAMPUS';
export const DELETE_CAMPUS = 'DELETE_CAMPUS';
export const UPDATE_CAMPUS = 'UPDATE_CAMPUS';
export const LOAD_STUDENTS = 'LOAD_STUDENTS';
export const SINGLE_STUDENT = 'SINGLE_STUDENT';
export const CREATE_STUDENT = 'CREATE_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';

export default {
  LOAD_CAMPUSES,
  UNLOAD,
  SINGLE_CAMPUS,
  CREATE_CAMPUS,
  DELETE_CAMPUS,
  UPDATE_CAMPUS,
  LOAD_STUDENTS,
  SINGLE_STUDENT,
  CREATE_STUDENT,
  DELETE_STUDENT,
  UPDATE_STUDENT,
};
